version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - 3306:3306
    env_file:
      - ./database/.env
    volumes:
      - ./database/mysql:/var/lib/mysql
